### PR TITLE
CameraVideoCapturer add change mirror mode method and fix default fro…

### PR DESCRIPTION
**Pull request by Tans5**
…nt camera wrong mirror state.

### 🎯 Goal
Default front camera mirror state is wrong and I add a method to change mirror mode.

### 🛠 Implementation details
Add `CameraVideoCapturer#mirrorCamera()` to change camera mirror state and remove default front camera use mirror mode.  
Add `CameraVideoCapturer#isMirrorCamera()` to check camera mirror state.   
Add `CameraVideoCapturer#isUsingFrontCamera()` to check if using front camera.  

### ✍️ Explain examples

```Kotlin
val videoCapture = Camera2Capturer(context, targetIds ?: ids.firstOrNull(), null)
// make camera mirror
videoCapture.mirrorCamera(true)
```

### Preparing a pull request for review
Ensure your change is properly formatted by running:

```gradle
$ ./gradlew spotlessApply
```

Please correct any failures before requesting a review.

### CODE REVIEW

**Comment by Tans5** [comment]
> Looks good to me! Would you mirror this PR on this [Getstream/webrtc](https://github.com/GetStream/webrtc) repository as well? Because this library is built top of that repository.

I'm not good at C++, so it's too difficult for me.

**Comment by skydoves** [comment]
I mean that project also mirrors that WebRTC Java files: https://github.com/GetStream/webrtc/blob/05c2ec7e1b74e9ed1875cc32833cae835bf64d2d/sdk/android/src/java/org/webrtc/Camera1Session.java#L4

**Comment by Tans5** [comment]
Ok, I will do this. 😂

**Comment by Tans5** [comment]
https://github.com/GetStream/webrtc/pull/38

**Pull request closed without merging**
