### PR TITLE
Add H264 hardware decoding for Marvell chips

### PR DESCRIPTION
**Pull request by tao1**
### 🎯 Goal
Add support for H264 hardware decoding on Bouygues Telecom's AndroidTV boxes relying on Marvell chips.

### 🛠 Implementation details
Describe the implementation details for this Pull Request.
- Add `MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible` to `MediaCodecUtils.DECODER_COLOR_FORMATS`
- Claim `MediaCodecVideoDecoderFactory.isH264HighProfileSupported()` returns `true` for Marvell chips

### ✍️ Explain examples
Sorry, example code is proprietary.

### Preparing a pull request for review
spotlessApply is OK

### CODE REVIEW

**Comment by tao1** [comment]
I didn't want my second commit to be part of this pull request. My mistake.

**Comment by skydoves** [comment]
Hey @tao1, thanks for creating this PR. The Stream team is working on `webrtc` core on [a separated repository](https://github.com/GetStream/webrtc) for the source of truth, would you create a PR for this here? Thank you!

https://github.com/GetStream/webrtc/blob/b33e7bdf77a950dd5e94a442bc9ddb518aec0cda/sdk/android/src/java/org/webrtc/MediaCodecUtils.java#L1

**Comment by tao1** [comment]
https://github.com/GetStream/webrtc/pull/23

**Comment by skydoves** [comment]
This issue has been contained in the latest release, so I'm closing this issue now. Thank you for your contribution, @tao1!

**Comment by tao1** [comment]
@skydoves
AFAIK it is not contained in latest release.
I guess because https://github.com/GetStream/webrtc/pull/23 was merged into https://github.com/GetStream/webrtc/tree/patch/m114 branch but it is still not merged into main.
You can verify Marvell chips are not checked in 1.1.1 release at https://github.com/GetStream/webrtc-android/blob/1.1.1/stream-webrtc-android/src/main/java/org/webrtc/MediaCodecVideoDecoderFactory.java#L131

KR

**Pull request closed without merging**
